name: Generate Pacman

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate light Pacman
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: abhayioadi

      - name: Prepare output
        run: |
          mkdir -p dist
          # Copy the generated pacman file to dist/
          cp pacman-contribution-graph.svg dist/pacman-contribution-graph.svg
          # Also copy it as the dark version so the links don't break, since the exact action for dark theme isn't standardized.
          cp pacman-contribution-graph.svg dist/pacman-contribution-graph-dark.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
